[tool.poetry]
name = "rag-conversation"
version = "0.1.0"
description = "Conversational RAG using Pinecone"
authors = [
    "Lance Martin <lance@langchain.dev>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
langchain = "^0.1"
chromadb = ">=0.4.14"
gpt4all = ">=2.3.2"
tiktoken = ">=0.5.1"
beautifulsoup4 = "^4.12.2"
langchain-text-splitters = ">=0.0.1,<0.1"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"

[tool.langserve]
export_module = "rag_conversation"
export_attr = "chain"

[tool.templates-hub]
use-case = "rag"
author = "Elastic"
integrations = ["OpenAI", "Pinecone"]
tags = ["vectordbs"]

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
